[package]
name = "airline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "airline"
path = "src/server/mod.rs"
crate-type = ["lib"]

[[bin]]
name = "airline"
path = "src/main.rs"

[dependencies]
